name: 서비스 빌드
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

env:
  IMAGE_TAG: ${{ inputs.image-tag || 'latest' }}
  IMAGE_NAME: ${{ inputs.image-name }}
  ENVIRONMENT: ${{ inputs.environment || 'prod' }}

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 애드온 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 이미지 빌드하고 푸쉬하기
        id: build-image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ENVIRONMENT: ${{ inputs.environment }}

        run: |
          echo "IMAGE_TAG=$IMAGE_TAG, IMAGE_NAME=$IMAGE_NAME" &&
          chmod +x ./gradlew &&
          ./gradlew jib

      - name: Slack 빌드 성공 알림
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author, workflowRun, pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '#59f764',
                title: `⛴️ 스프링 컨테이너 빌드 완료!`,
                fields: [
                  {
                    title: '배포 환경',
                    value: `${process.env.ENVIRONMENT}`,
                    short: true,
                  },
                  {
                    title: '배포자',
                    value: `${process.env.AS_AUTHOR}`,
                    short: true,
                  },
                  {
                    title: '워크플로 링크',
                    value: `${process.env.AS_WORKFLOW_RUN}`,
                    short: true,
                  },
                  {
                    title: 'PR 링크',
                    value: `${process.env.AS_PULL_REQUEST}`,
                    short: true,
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack CICD 실패 알림
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author, workflowRun, pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '#CA0025',
                title: `⛴️ 스프링 컨테이너 빌드 실패!`,
                fields: [
                  {
                    title: '배포 환경',
                    value: `${process.env.ENVIRONMENT}`,
                    short: true,
                  },
                  {
                    title: '배포자',
                    value: `${process.env.AS_AUTHOR}`,
                    short: true,
                  },
                  {
                    title: '워크플로 링크',
                    value: `${process.env.AS_WORKFLOW_RUN}`,
                    short: true,
                  },
                  {
                    title: 'PR 링크',
                    value: `${process.env.AS_PULL_REQUEST}`,
                    short: true,
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
